INSERT INTO USERS (USERS_NO, ID, PASSWORD, NAME, BIRTHDAY, GENDER, PHONE, PROVIDER, DELETED)
VALUES (USERS_NO_SEQ.NEXTVAL, 'user1', 1111, '테스트 사용자1', sysdate, '남', '010-1234-5678', 'LOCAL', 0);
INSERT INTO USERS (USERS_NO, ID, PASSWORD, NAME, BIRTHDAY, GENDER, PHONE, PROVIDER, DELETED)
VALUES (USERS_NO_SEQ.NEXTVAL, 'user2', 2222, '테스트 사용자2', sysdate, '남', '010-1234-5678', 'LOCAL', 0);
INSERT INTO USERS (USERS_NO, ID, PASSWORD, NAME, BIRTHDAY, GENDER, PHONE, PROVIDER, DELETED)
VALUES (USERS_NO_SEQ.NEXTVAL, 'user3', 3333, '테스트 사용자3', sysdate, '남', '010-1234-5678', 'LOCAL', 0);
INSERT INTO USERS (USERS_NO, ID, PASSWORD, NAME, BIRTHDAY, GENDER, PHONE, PROVIDER, DELETED)
VALUES (USERS_NO_SEQ.NEXTVAL, 'user4', 4444, '테스트 사용자4', sysdate, '남', '010-1234-5678', 'LOCAL', 0);
INSERT INTO USERS (USERS_NO, ID, PASSWORD, NAME, BIRTHDAY, GENDER, PHONE, PROVIDER, DELETED)
VALUES (USERS_NO_SEQ.NEXTVAL, 'user5', 5555, '테스트 사용자5', sysdate, '남', '010-1234-5678', 'LOCAL', 0);
